config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :clients
  root :to => 'clients#index'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :clients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :accounts, dependent: :destroy,foreign_key: "clients_id"
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.page(params[:page]).per(10)
    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Busquedas >>>>>>>>>>>>>>>>>>>>>>>>>>
    if params[:search].present?
      @busqueda = params[:search].rstrip
      puts @busqueda
      consulta = "(Numero_Cuenta LIKE :datos OR Pertenece_A LIKE :datos )"
      @accounts = Account.select("accounts.*").where(consulta, datos: "%#{@busqueda}%").order('created_at DESC').page(params[:page]).per(10)
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json

  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def account_params
    params.require(:account).permit(:Numero_Cuenta, :Pertenece_A, :String, :clients_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.page(params[:page]).per(10)

    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Busquedas >>>>>>>>>>>>>>>>>>>>>>>>>>
    if params[:search].present?
      @busqueda = params[:search].rstrip
      puts @busqueda
      consulta="(clients.Nombre LIKE :datos OR clients.Apellido_Paterno LIKE :datos OR Apellido_Materno LIKE :datos )"
      @clients = Client.select("clients.*").where(consulta, datos: "%#{@busqueda}%").order('created_at DESC').page(params[:page]).per(10)
      end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:Nombre, :Apellido_Paterno, :Apellido_Materno, :Edad, :Telefono, :Calle, :Colonia, :Numero_De_Casa, :Municipio)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/accounts/_accountabla.html.erb
<%# <%********************* Sweetalert No Results *************************** %>
<% if @error.present? %>
  <script>
      swal({
          title: "Advertencia", text: "No se encontraron resultados", type: "warning"
      });
  </script>
<% end %>
<%# <%********************** Paginacion & Boton Crear *******************************%>
<div class="row">
  <div class="col-xs-12 col-md-4">
    <%= link_to '<span class="fa fa-cc-mastercard "></span> '.html_safe + 'Nuevo', new_account_path, :class => 'btn btn-primary btn-xs btx' %>
  </div>
  <div class="col-xs-12 col-md-8 form-group" align="right">
    <div class="detall_right">
      <% if @accounts.length == 1 %>
        <%= page_entries_info @accounts, entry_name: "Cuenta" %>
      <% else %>
        <%= page_entries_info @accounts, entry_name: "Cuenta".pluralize() %>
      <% end %>
    </div>
    <div class="pag_right">
      <%= paginate @accounts, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true %>
    </div>
  </div>
</div>

<%# <%********************** Tabla Clientes *******************************%>
<div id="tabla_cuentas" style="overflow: auto;">
  <table class="table footable no-paging">
    <thead>
    <tr>
      <th class="text-left" data-sort-ignore="true">Numero cuenta</th>
      <th class="text-center" data-sort-ignore="true">Pertenece a</th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Mostrar</th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Editar</th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Eliminar</th>
    </tr>
    </thead>

    <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td class="text-left" data-sort-ignore="true">
          ************<%= account.Numero_Cuenta.last(4)%>
        </td>
        <td class="text-center" data-sort-ignore="true">
          <%= account.Pertenece_A%>
        </td>
        <td class="text-center"><%= link_to '<i class="fa fa-file-text"></i>'.html_safe, account, class: "btn btn-xs btn-primary btx", :data => {toggle: "tooltip"}, title: "Mostrar" %></td>
        <td class="text-center"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_account_path(account), class: "btn btn-xs btn-warning btx", :data => {toggle: "tooltip"}, title: "Editar" %></td>
        <td class="text-center">
          <button class="btn btn-danger btn-xs  accounts" type="button" id="<%= account.id %>" data-toggle="tooltip" title="Eliminar">
            <i class="fa fa-trash-o"></i>
          </button>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%# <%********************** Paginacion & Boton Crear *******************************%>
<div class="row">
  <div class="col-xs-12 col-md-4">
    <%= link_to '<span class="fa fa-cc-mastercard "></span> '.html_safe + 'Nuevo', new_account_path, :class => 'btn btn-primary btn-xs btx' %>
  </div>
  <div class="col-xs-12 col-md-8 form-group" align="right">
    <div class="detall_right">
      <% if @accounts.length == 1 %>
        <%= page_entries_info @accounts, entry_name: "Cuenta" %>
      <% else %>
        <%= page_entries_info @accounts, entry_name: "Cuenta".pluralize() %>
      <% end %>
    </div>
    <div class="pag_right">
      <%= paginate @accounts, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true %>
    </div>
  </div>
</div>

app/views/accounts/_form.html.erb
<%= form_for @account , :html => {:id => 'form1'} do |f| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-2 col-lg-2"></div>
    <div class="col-xs-6 col-lg-7">
      <div class="row">
        <div class="col-xs-12">
          <div class="field">
            <p class="text-center">
              <label>Número de Cuenta</label>
              <%= f.text_field :Numero_Cuenta, id: 'num', class: 'form-control', autocomplete: 'off',placeholder: " ************1234", :required => true, :maxlength => 16 %>
              <small id="numlab" style="display: none;">.</small>
            </p>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="field">
            <p class="text-center">
              <center>
                  <%= f.hidden_field :clients_id, value: params[:id_client]  %>
                  <% if Client.find_by_id(params[:id_client]).present? %>
                    <% u = Client.find_by_id(params[:id_client]) %>
                    <%= "#{u.name} #{u.last_name}" %>
                  <%else%>
                    <%= f.collection_select :clients_id, Client.all, :id, :Nombre , {prompt: true} , {class: 'form-control' } %>
                  <% end %>
              </center>
            </p>
          </div>
        </div>
      </div>


      <div class="col-xs-12 hr-line-dashed"></div>
      <div class="col-xs-12">
        <div class="actions">
          <button type="submit" , class="btn btn-xs btn-primary " , value=" Guardar" , name="btnSave">
            <i class="fa fa-user">Guardar</i>
          </button>
          <%= link_to '<span class="fa fa-user" ></span>  '.html_safe + " Cancelar", accounts_path, :class => 'btn btn-xs btn-warning btx' %>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight" style="padding-top: 0px;">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h1>Editar Cuenta</h1>
          <%# <%****************************** Body *********************************** %>
          <div class="ibox-content">
            <%= render 'form', account: @account %>
          </div>
          <%# <%****************************** Body *********************************** %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/index.js.erb
$("#accountabla").html("<%= escape_javascript(render("accountabla")) %>");
$('table').footable({paginate: false});
if ($(window).width() <= 425) {
  var hlp = document.getElementById('ayuda')
  hlp.parentNode.removeChild(hlp);
  document.getElementById('btnrt').innerHTML="<i class='fa fa-search'></i>"
  document.getElementById('searchbar').style.padding = "0px"
  var x = document.getElementsByClassName("btx");
  var i;
  for (i = 0; i < x.length; i++) {
     x[i].classList.remove('btn-xs');
     x[i].classList.add('btn-block');
   }
}

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

app/views/accounts/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight" style="padding-top: 0px;">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h1>Mostrar Cuenta</h1>
          <div align="center">
            <strong>Numero cuenta:</strong>
            <%= @account.Numero_Cuenta %>
            </p>

            <p>
              <strong>Pertenece a:</strong>
              <%= @account.Pertenece_A %>
            </p>
          </div>
          <div class="row">
          <div id="botones" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + "Editar", edit_account_path(@account), :class => 'btn btn-xs btn-primary btx' %>
            <%= link_to '<span class="fa fa-users" ></span> '.html_safe + "Volver", accounts_path, :class => 'btn btn-xs btn-warning btx' %>
          </div>
        </div>

        <%# <%****************************** Body *********************************** %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/clients/_clientabla.html.erb
<%# <%********************* Sweetalert No Results *************************** %>
<% if @error.present? %>
  <script>
      swal({
          title: "Advertencia", text: "No se encontraron resultados", type: "warning"
      });
  </script>
<% end %>
<%# <%********************** Paginacion & Boton Crear *******************************%>
<div class="row">
  <div class="col-xs-12 col-md-4">
    <%= link_to '<span class="fa fa-user"></span> '.html_safe + 'Nuevo', new_client_path, :class => 'btn btn-primary btn-xs btx' %>
  </div>
  <div class="col-xs-12 col-md-8 form-group" align="right">
    <div class="detall_right">
      <% if @clients.length == 1 %>
        <%= page_entries_info @clients, entry_name: "Cliente" %>
      <% else %>
        <%= page_entries_info @clients, entry_name: "Cliente".pluralize() %>
      <% end %>
    </div>
    <div class="pag_right">
      <%= paginate @clients, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true %>
    </div>
  </div>
</div>

<%# <%********************** Tabla Clientes *******************************%>
<div id="tabla_clientes" style="overflow: auto;">
  <table class="table footable no-paging">
    <thead>
    <tr>
      <th class="text-left" data-sort-ignore="true">Nombre</th>
      <th class="text-center" data-sort-ignore="true">Apellido paterno</th>
      <th class="text-center" data-sort-ignore="true">Apellido materno</th>
      <td class="text-center" data-sort-ignore="true">Total Cuentas</td>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Mostrar</th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Editar</th>
      <th class="text-center" data-sort-ignore="true" data-hide="phone">Eliminar</th>
    </tr>
    </thead>
    <tbody>
    <% @clients.each do |client| %>
      <tr class="footable-even">
        <td class="text-left"><%= client.Nombre %></td>
        <td class="text-center"><%= client.Apellido_Paterno %></td>
        <td class="text-center"><%= client.Apellido_Materno %></td>
        <td class="text-center">
          <% if client.accounts.present? %>
              <% if client.accounts.count > 0 %>
                  <%=client.accounts.count%>
            <% else %>
              0
            <%end%>
          <% else %>
            0
          <%end%>
        </td>
        <td class="text-center" ><%= link_to '<i class="fa fa-file-text"></i>'.html_safe, client, class:"btn btn-xs btn-primary btx", :data =>{toggle:"tooltip"}, title: "Mostrar"  %></td>
        <td class="text-center"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_client_path(client) , class:"btn btn-xs btn-warning btx", :data =>{toggle:"tooltip"}, title:"Editar"%></td>
        <td class="text-center">
          <button class="btn btn-danger btn-xs  clients" type="button" id="<%= client.id %>" data-toggle="tooltip" title="Eliminar">
            <i class="fa fa-trash-o"></i>
          </button>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%# <%********************** Tabla Clientes *******************************%>
<%# <%********************** Paginacion & Boton Crear *******************************%>
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <%= link_to '<span class="fa fa-user"></span> '.html_safe + 'Nuevo', new_client_path, :class => 'btn btn-primary btn-xs btx' %>
    </div>
    <div class="col-xs-12 col-md-8 form-group" align="right">
      <div class="detall_right">
        <% if @clients.length == 1 %>
          <%= page_entries_info @clients, entry_name: "Cliente" %>
        <% else %>
          <%= page_entries_info @clients, entry_name: "Cliente".pluralize() %>
        <% end %>
      </div>
      <div class="pag_right">
        <%= paginate @clients, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm", :remote => true %>
      </div>
    </div>
  </div>





app/views/clients/_form.html.erb
<%= form_for @client, :html => {:id => 'form1'} do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-2 col-lg-2"></div>
    <div class="col-xs-6 col-lg-7">
      <div class="row">
        <div class="col-xs-6">
          <div class="field">
            <p class="text-center">
              <label>Nombre</label>
              <%= f.text_field :Nombre, class: 'form-control', autocomplete: 'off', style: "text-transform:uppercase", placeholder: " Nombre", :id => "name", :maxlength => 255, :required => true %>
              <small id="labname" style="display: none;">.</small>
            </p>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="field">
            <p class="text-center">
              <label>Apellido Paterno</label>
              <%= f.text_field :Apellido_Paterno, class: 'form-control', autocomplete: 'off', style: "text-transform:uppercase", placeholder: " Apellido Paterno", :id => "ap", :maxlength => 255, :required => true %>
              <small id="labap" style="display: none;">.</small>
            </p>
          </div>
        </div>
      </div>


      <div class="col-xs-6">
        <div class="field">
          <p class="text-center">
            <label>Apellido Materno</label>
            <%= f.text_field :Apellido_Materno, class: 'form-control', autocomplete: 'off', style: "text-transform:uppercase", placeholder: " Apellido Materno", :id => "am", :maxlength => 255, :required => true %>
            <small id="labam" style="display: none;">.</small>
          </p>
        </div>
      </div>


      <div class="col-xs-6">
        <div class="field" id="dato_1">
          <p class="text-center">
            <label> Edad</label>
          <div class="input-group date">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            <%= f.text_field :Edad, class: "form-control", :placeholder => "MM/DD/YYYY", :autocomplete => "off", :id => "age", :name => 'age' , :required => true %>
          </div>
          <small id="labage" style="display: none;">.</small>
          <font color="#8b0000"><label id="errorBirth" style="display: none;"></label></font>
          </p>
        </div>
      </div>


      <div class="col-xs-6">
        <div class="field">
          <div align="center" class="form-group">
            <label>Telefono</label>
            <%= f.text_field :Telefono,  class: "form-control", autocomplete: "off", name: "phone", id: "phon", placeholder: "(55) 99-99-99-99", :maxlength => 10   %>
            <small id="labphon" style="display: none;">.</small>
          </div>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="field">
          <div align="center" class="form-group">
            <label>Calle</label>
            <%= f.text_field :Calle, class: 'form-control', autocomplete: 'off', placeholder: " Calle", :id => "add", :maxlength => 255 , :required => true %>
            <small id="labadd" style="display: none;">.</small>
          </div>
        </div>
      </div>


      <div class="col-xs-6">
        <div class="field">
          <div align="center" class="form-group">
            <label>Colonia</label>
            <%= f.text_field :Colonia, class: 'form-control', autocomplete: 'off', placeholder: " Colonia", :id => "col", :maxlength => 255, :required => true  %>
            <small id="labcol" style="display: none;">.</small>
          </div>
        </div>
      </div>


      <div class="col-xs-6">
        <div class="field">
          <div align="center" class="form-group">
            <label>Número de Casa</label>
            <%= f.text_field :Numero_De_Casa, class: 'form-control', autocomplete: 'off', placeholder: " Número de Casa", :id => "casa", :maxlength => 3, :required => true %>
            <small id="labcasa" style="display: none;">.</small>
          </div>
        </div>
      </div>


      <div class="col-xs-6">
        <div class="field">
          <div align="center" class="form-group">
            <label>Municipio</label>
            <%= f.text_field :Municipio, class: 'form-control', autocomplete: 'off', placeholder: " Municipio", :id => "mun", :maxlength => 255, :required => true  %>
            <small id="labmun" style="display: none;">.</small>
          </div>
        </div>
      </div>

      <!--            <div class="actions">-->
      <%#= f.submit %>
      <!--            </div>-->
      <div class="col-xs-12 hr-line-dashed"></div>
      <div class="col-xs-12">
        <div class="actions">
          <button type="submit" , class="btn btn-xs btn-primary " , value=" Guardar" , name="btnSave">
            <i class="fa fa-user">Guardar</i>
          </button>
          <%= link_to '<span class="fa fa-user" ></span>  '.html_safe + " Cancelar", clients_path, :class => 'btn btn-xs btn-warning btx' %>
        </div>

      </div>
    </div>
  </div>
<% end %>

<script>
    //>>>>>>>>>>>>>>>>>>>>>>> JQuery <<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    $(document).ready(function () {
//********************** Data Mask ***************************

        $("#phon").mask("(99) 9999-9999");
        $("#age").mask("99/99/9999")

        jQuery(function ($) {
            $("#phon").focusout(function () {
                var valor = $(this).val();
                valor = valor.replace("(", "")
                valor = valor.replace("_", "")
                valor = valor.replace("_", "")
                valor = valor.replace(")", "")
                valor = valor.replace(" ", "")
                valor = valor.replace("_", "")
                valor = valor.replace("_", "")
                valor = valor.replace("_", "")
                valor = valor.replace("_", "")
                valor = valor.replace("-", "")
                valor = valor.replace("_", "")
                valor = valor.replace("_", "")
                valor = valor.replace("_", "")
                valor = valor.replace("_", "")

                if (valor.length < 10) {
                    $("#phon").val("");
                }
            })
        });
    });
</script>

app/views/clients/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight" style="padding-top: 0px;">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h1>Editar Cliente</h1>
          <%# <%****************************** Body *********************************** %>
          <div class="ibox-content">
          <%= render 'form', client: @client %>
          </div>
          <%# <%****************************** Body *********************************** %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/index.js.erb
$("#clientabla").html("<%= escape_javascript(render("clientabla")) %>");
$('table').footable({paginate: false});
if ($(window).width() <= 425) {
  var hlp = document.getElementById('ayuda')
  hlp.parentNode.removeChild(hlp);
  document.getElementById('btnrt').innerHTML="<i class='fa fa-search'></i>"
  document.getElementById('searchbar').style.padding = "0px"
  var x = document.getElementsByClassName("btx");
  var i;
  for (i = 0; i < x.length; i++) {
     x[i].classList.remove('btn-xs');
     x[i].classList.add('btn-block');
   }
}

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight" style="padding-top: 0px;">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h1>Mostrar Cliente</h1>

          <div align="center">
            <strong>Nombre:</strong>
            <%= @client.Nombre %>
            </p>

            <p>
              <strong>Apellido paterno:</strong>
              <%= @client.Apellido_Paterno %>
            </p>

            <p>
              <strong>Apellido materno:</strong>
              <%= @client.Apellido_Materno %>
            </p>

            <p>
              <strong>Edad:</strong>
              <%= @client.Edad %>
            </p>

            <p>
              <strong>Telefono:</strong>
              <%= @client.Telefono %>
            </p>

            <p>
              <strong>Calle:</strong>
              <%= @client.Calle %>
            </p>

            <p>
              <strong>Colonia:</strong>
              <%= @client.Colonia %>
            </p>

            <p>
              <strong>Numero de casa:</strong>
              <%= @client.Numero_De_Casa %>
            </p>

            <p>
              <strong>Municipio:</strong>
              <%= @client.Municipio %>
            </p>
          </div>
          <div class="row">
            <div id="botones" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <%= link_to '<span class="fa fa-users" ></span>  '.html_safe + "Editar", edit_client_path(@client), :class => 'btn btn-xs btn-primary btx' %>
              <%= link_to '<span class="fa fa-users" ></span> '.html_safe + "Volver", clients_path, :class => 'btn btn-xs btn-warning btx' %>
            </div>
          </div>

          <%# <%****************************** Body *********************************** %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    if ($(window).width() <= 425) {
        document.getElementById("botones").style.display = "inline-grid"
        var x = document.getElementsByClassName("btx");
        var i;
        for (i = 0; i < x.length; i++) {
            x[i].classList.remove('btn-xs');
            x[i].classList.add('btn-block');
        }
    }
</script>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="text-center">
      KS Soluciones S.A. de C.V. &copy; 1998-<%= Time.now.year %>
    </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
  <nav class="navbar navbar-static-top white-bg" role="navigation">
    <div class="navbar-header">
      <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
      <li>
        <span class="m-r-sm text-muted welcome-message">Bienvenido </span>
      </li>
<!--      <li><i class="fa fa-sign-out"></i></li>-->
<!--      <li> <%#= link_to t('all.logout'), destroy_user_session_path, method: :delete %>-->
      <li>
        <a class="right-sidebar-toggle">
        </a>
      </li>
    </ul>
  </nav>
</div>